Scorpio Broker Intermediate Release 1.1.0
IndustryFusion/ScorpioBroker pull request #1
Opened 2021-11-11 12:05 UTC by subhommitra

Forked the ScorpioBroker repo for TCS. Any changes will be first made in this repo and a PR will then be raised to merge changes into the "TCS-development" branch in the IFF fork of Scorpio Broker.

2021-11-22 13:05 UTC, wagmarcel requested changes

2021-11-22 13:05 UTC, wagmarcel commented on Core/EntityManager/src/main/java/eu/neclab/ngsildbroker/entityhandler/controller/EntityController.java
> +	/*@GetMapping("/test")
Please remove commented out code from source or explain why it should stay there

2021-11-22 13:05 UTC, wagmarcel commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/config/KeycloakSecurityConfig.java
> +        http.csrf().disable();
Why it csrf disabled? Does it not apply here? If it could apply, can we make it at least configurable?

2021-11-22 13:05 UTC, wagmarcel commented on History/HistoryManager/src/main/java/eu/neclab/ngsildbroker/historymanager/config/KeycloakSecurityConfig.java
> +        http.csrf().disable();
see other csrf related comment

2021-11-22 13:05 UTC, wagmarcel commented on History/HistoryManager/src/main/java/eu/neclab/ngsildbroker/historymanager/controller/HistoryController.java
> +			@RequestBody(required = false) String payload, @RequestHeader String Authorization) {
Maybe I miss here something, or do not understand the Spring background: Why is the Authorization header added but not used in the code? For later checks?

2021-11-22 13:05 UTC, wagmarcel commented on Registry/RegistryManager/src/main/java/eu/neclab/ngsildbroker/registryhandler/controller/RegistryController.java
> +			@RequestParam(value = "qtoken", required = false) String qToken, @RequestHeader String Authorization) {
see other Authorization remark earlier

2021-11-24 12:49 UTC, Suvarat211 commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/config/KeycloakSecurityConfig.java
> +        http.csrf().disable();
Have disabled csrf on all the microservices as the APIs on these microservices are triggered by the gateway internally. The gateway is exposed to the clients of the microservices. We could configure csrf in the Spring Cloud Gateway if needed.

2021-11-24 12:55 UTC, wagmarcel commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/config/KeycloakSecurityConfig.java
> +        http.csrf().disable();
ok - if the api is not exposed to outer world, there is not problem, right?

2021-11-25 06:51 UTC, Suvarat211 commented on History/HistoryManager/src/main/java/eu/neclab/ngsildbroker/historymanager/controller/HistoryController.java
> +			@RequestBody(required = false) String payload, @RequestHeader String Authorization) {
Yes, included this for any checks on the Auth token and not using this param in the method now. Removed it in the latest commit for all the services.

2021-11-25 13:12 UTC, Suvarat211 commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/config/KeycloakSecurityConfig.java
> +        http.csrf().disable();
Yes. The Scorpio NGSI-LD APIs are not exposed to any external network and will remain on the Kubernetes internal network. Gateway is the only service that hits these APIs.

2021-11-25 13:14 UTC, Suvarat211 commented on Registry/RegistryManager/src/main/java/eu/neclab/ngsildbroker/registryhandler/controller/RegistryController.java
> +			@RequestParam(value = "qtoken", required = false) String qToken, @RequestHeader String Authorization) {
Addressed in the latest commit in all the services. Latest commit also includes support for new role, revised the roles names as discussed in review meeting

2021-11-25 13:18 UTC, Suvarat211 commented on Core/EntityManager/src/main/java/eu/neclab/ngsildbroker/entityhandler/controller/EntityController.java
> +	/*@GetMapping("/test")
Removed the commented code.

2021-11-25 13:22 UTC, Suvarat211 commented on History/HistoryManager/src/main/java/eu/neclab/ngsildbroker/historymanager/config/KeycloakSecurityConfig.java
> +        http.csrf().disable();
Same as above service. Disabled for all Scorpio internal services.

2021-11-25 15:13 UTC, wagmarcel approved these changes

2021-11-25 15:18 UTC, merged