SpringCloud config-server URI reference in Scorpio services
IndustryFusion/ScorpioBroker pull request #4
Opened 2021-12-05 09:43 UTC by swathichittajallu

Commits for this PR include:
1) Config server reference in application property files for Scorpio services.

2021-12-07 22:20 UTC, wagmarcel requested changes
Please follow the convention in https://cbea.ms/git-commit/
It is not sufficient to put description in PR comments. Description must be part of commit message.

2021-12-13 09:25 UTC, wagmarcel commented
Related issues are not mentioned in the commit message

2021-12-13 10:53 UTC, subhommitra commented
@wagmarcel Added issue reference to the commit message.

2021-12-13 11:00 UTC, wagmarcel approved these changes

2021-12-13 20:24 UTC, merged